import { Inter } from "next/font/google";
import "./globals.css";
import 'tailwindcss/tailwind.css';

// Initialize Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for the webpage
export const metadata = {
  title: "Weather Dashboard",
  description: "Generated by Shweta Gatade using create next app ",
};

// Root layout component for the application
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
